version: '3'
services:
  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/.portainer/config:/data
    restart: always
    network_mode: host
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ${CONFIG_DIR}/.ha/config:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: host
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=dcop.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN} #optional
      - EMAIL=${EMAIL} #optional
    volumes:
      - ${CONFIG_DIR}/.swag/config:/config
    ports:
      - 4430:443
      - 8180:80 #optional
    restart: unless-stopped
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - ${CONFIG_DIR}/.duplicati/config:/config
      - ${CONFIG_DIR}:/source
    ports:
      - 8200:8200
    restart: unless-stopped
