version: '3'
services:
  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/.portainer/config:/data
    restart: always
    network_mode: host
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ${CONFIG_DIR}/.ha/config:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: host
  ddclient:
    image: ghcr.io/linuxserver/ddclient:arm32v7-3.10.0
    container_name: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/.ddclient/config:/config
    restart: unless-stopped
  swag:
    image: linuxserver/swag:arm32v7-2.6.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=coppolino.me
      - SUBDOMAINS=plex,homeassistant
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - EMAIL=${EMAIL} #optional
    volumes:
      - ${CONFIG_DIR}/.swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
