version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ${CONFIG_DIR}/.ha/config:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    network_mode: host
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TZ}
    volumes:
      - '${CONFIG_DIR}/.pihole/etc-pihole/:/etc/pihole/'
      - '${CONFIG_DIR}/.pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=dcop.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN} #optional
      - EMAIL=${EMAIL} #optional
    volumes:
      - ${CONFIG_DIR}/.letsencrypt/config:/config
    ports:
      - 4430:443
      - 8180:80 #optional
    restart: unless-stopped
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - ${CONFIG_DIR}/.duplicati/config:/config
      - ${CONFIG_DIR}:/source
    ports:
      - 8200:8200
    restart: unless-stopped
